root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/api"
bin = "tmp/main"
delay = 1000
exclude_dir = ["tmp", "vendor", "node_modules"]
include_ext = ["go", "tpl", "tmpl", "html"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
